[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]☁️ Kai节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]DIRECT
;custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=👋 手动切换`select`.*
custom_proxy_group=☁️ Kai节点`select`(爪云|kai|一方|104|xyz|org)
;custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇹🇼 台湾节点`url-test`(台湾|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|韩|Korea|KOR|首尔|韩国|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇬🇧 英国节点`url-test`(GB|英国|英格兰|伦敦)`http://www.gstatic.com/generate_204`900,,50
;custom_proxy_group=🇫🇷 法国节点`url-test`(FR[^A]|法国|巴黎|马赛)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇩🇪 德国节点`url-test`(DE|德国|柏林|慕尼黑|法兰克福)`http://www.gstatic.com/generate_204`900,,50
;custom_proxy_group=🌏 亚太地区`select`(KR|韩|TW|台湾|RU|俄|AU|澳大利亚|AM|亚美尼亚|TR|土耳其|IS|以色列|KZ|哈萨克|AE|阿联酋|SA|沙特|IR|伊朗|IQ|伊拉克|AF|阿富汗|IN|印度|PK|巴基斯坦|MO|澳门|KP|朝鲜|VN|越南|TH|泰国|MY|马来西亚|PH|菲律宾|KH|柬埔寨|MN|蒙古)
;custom_proxy_group=🌍️ 欧洲地区`select`(GB|英国|FR|法国|DE|德国|IT|意大利|CH|瑞士|ES|西班牙|[A^Z]PT|葡萄牙|NL|荷兰|DK|丹麦|SE|瑞典|FI|芬兰|NO|挪威|IS|冰岛|IE|爱尔兰|LT|立陶宛|EE|爱沙尼亚|LV|拉脱维亚|AT|奥地利|HU|匈牙利|PL[A^Z]|波兰|RO|罗马尼亚|BG|保加利亚|CZ|捷克|SK|斯洛伐克|MD|摩尔多瓦|UA|乌克兰|MK|北马其顿)
;custom_proxy_group=🌎 美洲节点`select`(CA|加拿大|MX|墨西哥|GL|格陵兰|CU|古巴|BM|百慕大|AR|阿根廷|BR|巴西|CL|智利|PE|秘鲁)
;custom_proxy_group=🗺️ 其它节点`select`(RU|俄|AU|澳大利亚|NZ|新西兰|FJ|斐济|EG|埃及|SO|索马里|NG|尼日利亚|ZA|南非|AQ|南极|CA|加拿大|MX|墨西哥|GL|格陵兰|CU|古巴|BM|百慕大|AR|阿根廷|BR|巴西|CL|智利|PE|秘鲁)
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`.*

include_remarks=(爪云|kai|一方|104|xyz|org|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|新加坡|坡|狮城|SG|Singapore|美|波特兰|洛杉矶|圣何塞|西雅图|芝加哥|US|United States)
exclude_remarks=(群组|频道)
enable_rule_generator=true
overwrite_original_rules=true

